### ISSUE TITLE
Cannot init shared memories

### ISSUE THREAD

**Issue by patternspandemic** [pietroalbini/botogram#20]
Hi Pietro,

On the master branch, I'm running into this TypeError and cannot seem to use shared memory initializers. Any ideas?

```python
import botogram
bot = botogram.create('<API_TOKEN>')

@bot.init_shared_memory
def test_shared_memory(shared):
    shared["test"] = "memory"

if __name__ == "__main__":
    bot.run()
```

```
Traceback (most recent call last):
  File "..../botogram/runner/processes.py", line 54, in run
    self.loop()
  File "..../botogram/runner/processes.py", line 158, in loop
    job.process(self.bots)
  File "..../botogram/runner/jobs.py", line 87, in process
    return self.func(bot, self.metadata)
  File "..../botogram/runner/jobs.py", line 96, in process_update
    bot.process(update)
  File "..../botogram/frozenbot.py", line 183, in process
    result = hook.call(self, update)
  File "..../botogram/hooks.py", line 44, in call
    return self._call(bot, update)
  File "..../botogram/hooks.py", line 175, in _call
    bot._call(self.func, chat=message.chat, message=message, args=args)
  File "..../botogram/frozenbot.py", line 227, in _call
    shared = self._shared_memory.of(self._bot_id, component)
  File "..../botogram/shared.py", line 128, in of
    self.apply_inits(component, memory)
  File "..../botogram/shared.py", line 140, in apply_inits
    init(memory)
TypeError: 'SharedMemoryInitializerHook' object is not callable
```

Thanks, Brad

**Comment by pietroalbini** [comment]
While fixing this bug I found another bug, hold on.
