### ISSUE TITLE
botogram 0.2.x crashes with edited messages

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#70]
An user reported this crash on the Telegram group:

```
Traceback (most recent call last):
  File "C:\...\botogram\runner\processes.py", line 54, in run
    self.loop()
  File "C:\...\botogram\runner\processes.py", line 207, in loop
    if update.message.date < self.started_at:
AttributeError: 'NoneType' object has no attribute 'date'
```

**botogram version**: 0.2.1

**Comment by pietroalbini** [comment]
Apparently this has to do with edited messages, which creates trouble in botogram 0.2. Another traceback:

```
Traceback (most recent call last):
  File "/.../botogram/runner/processes.py", line 54, in run
    self.loop()
  File "/.../botogram/runner/processes.py", line 158, in loop
    job.process(self.bots)
  File "/.../botogram/runner/jobs.py", line 87, in process
    return self.func(bot, self.metadata)
  File "/.../botogram/runner/jobs.py", line 96, in process_update
    bot.process(update)
  File "/.../botogram/frozenbot.py", line 144, in process
    result = hook.call(self, update)
  File "/.../botogram/hooks.py", line 43, in call
    if self._only_texts and update.message.text is None:
```
